### ISSUE TITLE
The currency API is not working

### ISSUE THREAD

**Issue by wittyvik** [fawazahmed0/currency-api#1]
Getting error as Failed to fetch fawazahmed0/currency-api@1 from GitHub.

**Comment by fawazahmed0** [comment]
currency-api has stopped working, Please read the [migration guide](https://github.com/fawazahmed0/exchange-api/blob/main/MIGRATION.md)

**Comment by bhaktiagrawal088** [comment]
https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.json

it is working

**Comment by twin-star1** [comment]
api bad request , status=400

**Comment by Surajkumar01273** [comment]
currency converter api is not working 
give the error - Failed to fetch fawazahmed0/currency-api@1 from GitHub.

**Comment by itsur-mayur** [comment]
> https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.json
> 
> it is working

yes brother , its working!!
thank you for sharing this and have a nyc day
