### ISSUE TITLE
use for travel app?

### ISSUE THREAD

**Issue by travelBuf** [fawazahmed0/currency-api#22]
What is the source of your exchange rates? location / company
What time are the rates updated daily?

I am interested in using the rates in a travel app.
I had things working in SwiftUI until the date was added to the JSON file, now I'm stuck.

galendotsmith@gmail.com

**Comment by fawazahmed0** [comment]
> What is the source of your exchange rates? location / company

Google and bing

> What time are the rates updated daily?
by 00:30 UTC

**Comment by fawazahmed0** [comment]
I added the date because there was a request to add the timestamp:

https://github.com/fawazahmed0/currency-api/issues/21

**Comment by travelBuf** [comment]
Thanks for the info

**Comment by travelBuf** [comment]
Hi guys:

When I request your currency exchange rates with the base set to “usd” currently they are dated 2022-02-26 but when I change the base to “eur” the exchange rates are dated today (2022-03-02). Why the difference?

Galen Smith
Nevada, USA

**Comment by fawazahmed0** [comment]
see [this](https://github.com/fawazahmed0/currency-api/issues/39)
