### ISSUE TITLE
BYN currency issues

### ISSUE THREAD

**Issue by luntik2012** [fawazahmed0/currency-api#24]
this returns wrong result

`https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/byn.json`

there is no BYN currency here

`https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies.json`

BYN is a new code of Belarussia Ruble. There is only old code (BYR) which is not used for about 5 years and has wrong exchange rates in this repo.

**Comment by fawazahmed0** [comment]
Thanks for reporting this issue, you can check the link again tomorrow (it will take some time to pick up new updates), hopefully it should work fine.
or you can also test new updates with another currency like :
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/eur/byn.json

**Comment by luntik2012** [comment]
works eur/byn and rub/byn, doesn't work with usd/byn

**Comment by fawazahmed0** [comment]
It will work from tomorrow
