### ISSUE TITLE
Missing September 14th data

### ISSUE THREAD

**Issue by kaleabmelkie** [fawazahmed0/currency-api#32]
2021-09-14 seems to be skipped. Is it possible to patch it now?

**Comment by fawazahmed0** [comment]
Github actions was [failing](https://github.com/fawazahmed0/currency-api/commits/1?after=c2c7938e748d4047b493717e9cd29a1a8c670df3+104&branch=1) on that day. That's why the data is not available.
There is not much I could do.

**Comment by fawazahmed0** [comment]
Also don't forget to use fallback urls, otherwise you will face issues, for example if you want to fetch usd to eur rate:

```js
const fetchWithFallback = async (links,obj) => {
  let response;
  for(let link of links)
  {  try{
      response = await fetch(link,obj)
      if(response.ok)
          return response
        }catch(e){}
  }
   return response
}

fetchWithFallback(["https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/eur.min.json","https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd/eur.json"]).then(res => res.json()).then(console.log)


```

**Comment by RahulKini** [comment]
No data from 20-08 until 08-11?

**Comment by fawazahmed0** [comment]
please see [this](https://github.com/fawazahmed0/currency-api/issues/89)

**Comment by ArakyHerlambang** [comment]
### _****_

**Comment by ArakyHerlambang** [comment]
>

**Comment by ArakyHerlambang** [comment]
[``](url)
