### ISSUE TITLE
Error when getting `latest` via explicit date

### ISSUE THREAD

**Issue by aleemb** [fawazahmed0/currency-api#33]
Assuming today is 25th December, the following URL fails:

https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/2021-12-25/currencies/gbp/usd.json

    Package size exceeded the configured limit of 50 MB. Try https://github.com/fawazahmed0/currency-api/tree/1/2021-12-25/currencies/gbp/usd.json instead.*:

However, the below works, while still returning data for `2021-12-25`
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/gbp/usd.json

Getting the previous date's data also works:
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/2021-12-24/currencies/gbp/usd.json

**Comment by fawazahmed0** [comment]
You will need to use `latest` to get today's currency data, `YYYY-MM-DD` is for accessing historical data

**Comment by nrayburn-tech** [comment]
@fawazahmed0 would you accept a PR that writes to both `latest` and `YYYY-MM-DD` at the same time?

Always having `YYYY-MM-DD` makes it more convenient to consume the API.  Otherwise, a special case needs to be added for when the date is today, to use `latest` instead of `YYYY-MM-DD`.

**Comment by fawazahmed0** [comment]
I have added changes to write both `latest` & todaysDate (`YYYY-MM-DD`), but sometimes `YYYY-MM-DD` may not be available, so you should also consider that.
See this for more info: https://github.com/fawazahmed0/currency-api/issues/32
