### ISSUE TITLE
Add some currencies in the api

### ISSUE THREAD

**Issue by kevincaradant** [fawazahmed0/currency-api#38]
Hi

Firstly, Thanks for your job

I would know if it's possible that you add some currencies:
VET
ONE
EGLD
CHZ
GRT
1INCH
INJ
ENJ
KSM

Thank you :)

Regards

**Comment by joaovitoriasilva** [comment]
CRO would be awesome too. 
Thanks. :)

**Comment by fawazahmed0** [comment]
I actually scrape the data from some API, and it seems that only `ENJ` rate exists in that API. So only ENJ will get added. 
You should be able to access `ENJ` after 1-2 days.

**Comment by kevincaradant** [comment]
Alright, thanks. 

maybe it's because you can find it under the complete name?

Example : vet = vechain
Chz = chilliz
Grt = the graph
Ksm = kusama

**Comment by fawazahmed0** [comment]
ok, I have added all currencies, you guys have asked for
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/cro.json
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/vet.json
