### ISSUE TITLE
try to fetch currency api but browser show error

### ISSUE THREAD

**Issue by abhigaikwad25** [fawazahmed0/currency-api#4]
URL : https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/eur.json
ERROR : Failed to fetch fawazahmed0/currency-api@1 from GitHub.

**Comment by fawazahmed0** [comment]
please see [this](https://github.com/fawazahmed0/currency-api/issues/1#issuecomment-2005120328)
