### ISSUE TITLE
[Question] What time (in UTC) does the currency data get polled?

### ISSUE THREAD

**Issue by LucidThought** [fawazahmed0/currency-api#42]
When is the currency data queried each day? Is the data queried at the same time each day? If not, is there a way to get the timestamp that each conversion was measured when querying rates?

Conversion rates change throughout the day and I'd like to be able to advertise a timestamp when the data was polled.

**Comment by fawazahmed0** [comment]
the workflow runs at 00:00(utc), exact timestamp could be in range from 00:03utc to 00:10utc
