### ISSUE TITLE
Gold Gram Support

### ISSUE THREAD

**Issue by ahmeterenodaci** [fawazahmed0/currency-api#48]
Is it possible to add [gold gram](https://www.investing.com/currencies/gau-usd) to currency-api?

**Comment by fawazahmed0** [comment]
Can you provide source to an api, which provides this currency?

**Comment by ahmeterenodaci** [comment]
I found [this](https://metals-api.com/). It also contains other precious metals such as silver, platinum etc.

**Comment by fawazahmed0** [comment]
Ok thanks, I will add the rates into my api.  But it will take some time

**Comment by fawazahmed0** [comment]
silver(XAG), gold (XAU), and platinum(XPT) is now added in the API. The data will be available from tomorrow
