### ISSUE TITLE
Failed to fetch fawazahmed0/currency-api@1 from GitHub.

### ISSUE THREAD

**Issue by SW-YONTO** [fawazahmed0/currency-api#6]
how to fix this issue and tell me how to use it

**Comment by fawazahmed0** [comment]
please see [this](https://github.com/fawazahmed0/currency-api/issues/1#issuecomment-2005120328)

**Comment by BarshaRouth** [comment]
> how to fix this issue and tell me how to use it

https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies/usd.json

it's working
