### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by johnhorsema** [fawazahmed0/currency-api#62]
Several GET requests fail and gives the above error message.

https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/2022-12-06/currencies/hkd.min.json
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/2022-12-20/currencies/hkd.min.json

**Comment by fawazahmed0** [comment]
Today it's 2022-12-03 and you are using `2022-12-06` .
