### ISSUE TITLE
old exchange rates disappeared

### ISSUE THREAD

**Issue by vilmosnagy** [fawazahmed0/currency-api#66]
Hi,

a couple of weeks ago there were change rates since 2020-11-27 until the current day. But now the history is only going back until 2022-01-01.

Is there a way to reach the old currency rates?

Thanks,

**Comment by fawazahmed0** [comment]
The repository size was increasing daily and deleting the old rates was necessary.
Also I have already stated [here](https://github.com/fawazahmed0/currency-api#readme:~:text=Historical%20rates%20are%20only%20available%20for%20last%201%20year%20and%20some%20dates%20may%20be%20missing)  that only 1 year dates will be available.

The main reason for deleting old rates is that, If the repo size increases to above 5GB, there is a chance that GitHub may contact me to reduce the size or worst case they might ask me to take down the repo.

If accessing the old rates in necessary, then you can refer my [forks](https://github.com/fawazahmed0/currency-api/network/members), most of them should have the old data.

You need to change url:
`https://cdn.jsdelivr.net/gh/{forkUserName}/currency-api@1/2020-11-27/currencies/eur.json`

Example:
https://cdn.jsdelivr.net/gh/AayushAnand07/currency-api@1/2020-11-27/currencies/eur.json

**Comment by vilmosnagy** [comment]
Thanks,

I've forked a repository which constains all 2021 data here: https://github.com/vilmosnagy/currency-api-2021
