### ISSUE TITLE
i'm trying to fetch the API but it is not working...why??

### ISSUE THREAD

**Issue by BlAcKyCoDe50** [fawazahmed0/currency-api#7]
I am making a mini project i am using this API but failed to fetch the API...

![API_issue](https://github.com/fawazahmed0/currency-api/assets/117261834/4b16c6e1-0b03-4394-86af-5f18b4995a64)

**Comment by fawazahmed0** [comment]
currency-api has stopped working, Please read the [migration guide](https://github.com/fawazahmed0/exchange-api/blob/main/MIGRATION.md)

**Comment by BlAcKyCoDe50** [comment]
Still it is not accessible
https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@%7Bdate%7D/v1/%7Bendpoint%7D

**Comment by fawazahmed0** [comment]
refer the links given at [here](https://github.com/fawazahmed0/exchange-api?tab=readme-ov-file#endpoints)
