### ISSUE TITLE
Package size exceeded the configured limit of 50 MB.

### ISSUE THREAD

**Issue by iagliukov** [fawazahmed0/currency-api#74]
HI,
First of all thank you to that service but today i can't parse the data. Is it my mistake or any problem with data?

**Comment by vonElfvin** [comment]
Seems like the data for 2023-05-05 is missing

**Comment by fawazahmed0** [comment]
Please see [this](https://github.com/fawazahmed0/currency-api/issues/32#issuecomment-985270590)

**Comment by fawazahmed0** [comment]
Github action failed on [2023-05-05](https://github.com/fawazahmed0/currency-api/actions/runs/4888812860)
