### ISSUE TITLE
These two in circulation currencies are missing MRU, STN

### ISSUE THREAD

**Issue by absar** [fawazahmed0/currency-api#77]
These two in circulation currencies are missing:
`MRU` Mauritanian ouguiya
`STN` São Tomé and Príncipe dobra

**Comment by absar** [comment]
@fawazahmed0 can you look into it

**Comment by fawazahmed0** [comment]
could you provide me link to an api, where these currencies are available

**Comment by absar** [comment]
Yahoo finance supports both, it might need a cookie and crumb based on the requesting country.
https://query1.finance.yahoo.com/v7/finance/quote?symbols=USDMRU=X,USDSTN=X&fields=regularMarketPrice
https://query2.finance.yahoo.com/v10/finance/quoteSummary/USDMRU=X?

**Comment by fawazahmed0** [comment]
> it might need a cookie

That would make things complicated. 

I need an API which provides some free requests/month, so that I could scrape those currencies data.
Are those currencies available in [here](https://github.com/public-apis/public-apis#currency-exchange) or [here](https://www.google.com/search?q=currency+api)

**Comment by absar** [comment]
Yes both are available in your first link under CurrencyFreaks [here](https://github.com/public-apis/public-apis#currency-exchangel)

**Comment by fawazahmed0** [comment]
new currencies should be available from 24-07-23, let me if there are any issues with the rates. I haven't tested the [newly added code](https://github.com/fawazahmed0/currency-api/commit/4057b31833763347ac67b57a14594945143e113e) locally.

Also please note, I have deleted your previous comment, as it is against TOS of many currency api providers to scrape data from them.

**Comment by absar** [comment]
Thank you, that was quick. Sure will test and let you know when rates are available after 24th.

**Comment by absar** [comment]
The new currency rates match the ones displayed in the source API. Although the rates are not very accurate in the source itself, which of course is not an issue with your API. Thanks again.

**Comment by fawazahmed0** [comment]
I have added new api for accuracy. More accurate rates should be available from tomorrow
