### ISSUE TITLE
Failed to fetch details

### ISSUE THREAD

**Issue by mdas1998** [fawazahmed0/currency-api#8]
This API is not working.

**Comment by fawazahmed0** [comment]
please see [this](https://github.com/fawazahmed0/currency-api/issues/1#issuecomment-2005120328)

**Comment by Elite05-Ur** [comment]
not working 
plz correct it

**Comment by fawazahmed0** [comment]
currency-api has stopped working, Please read the [migration guide](https://github.com/fawazahmed0/exchange-api/blob/main/MIGRATION.md)
