### ISSUE TITLE
Instead of running cleanup yearly maybe run daily to clear anything older than last 365 days

### ISSUE THREAD

**Issue by absar** [fawazahmed0/currency-api#87]
Am not sure how cleanup works but if the architecture allows, instead of running cleanup yearly, maybe run daily to clear anything older than last 365 days, which in theory will clear just one day(oldest day if the job runs successfully everyday), reducing the time it takes to clear. This way the repo size will also remain constant with 365 days worth of data.

**Comment by fawazahmed0** [comment]
cleanup is a risky operation([due to force pushing in chunks](https://github.com/fawazahmed0/currency-api/blob/5644be452a2287fe2606ebf512ccae98f1407605/.github/workflows/cleanup-repo.yml#L80)), this is why its done yearly

**Comment by absar** [comment]
Thanks for the details. Hope the cleanup jobs finish soon, since the rates are not updated today.
